#!/bin/sh
###############################################################################
# $FILENAME
# Generated by generate_fw_modules_exceptions.sh
# Version: 2026-01-17
###############################################################################


# Alibaba – China HTTPS exceptions
iptables --wait -t filter -A CUSTOMFORWARD -p tcp --dport 443 -d 203.119.128.0/17 -j ACCEPT
iptables --wait -t filter -A CUSTOMFORWARD -p tcp --dport 443 -d 140.205.0.0/16 -j ACCEPT
iptables --wait -t filter -A CUSTOMFORWARD -p tcp --dport 443 -d 59.82.32.0/21   -j ACCEPT
iptables --wait -t filter -A CUSTOMFORWARD -p tcp --dport 443 -d 59.82.24.0/21   -j ACCEPT
iptables --wait -t filter -A CUSTOMFORWARD -p tcp --dport 443 -d 59.82.112.0/21  -j ACCEPT

iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp --dport 443 -d 203.119.128.0/17 -j ACCEPT
iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp --dport 443 -d 140.205.0.0/16   -j ACCEPT
iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp --dport 443 -d 59.82.32.0/21    -j ACCEPT
iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp --dport 443 -d 59.82.24.0/21    -j ACCEPT
iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp --dport 443 -d 59.82.112.0/21   -j ACCEPT

