#!/bin/sh
###############################################################################
# $FILENAME
# Manually Generated by H&M
# Version: 2026-03-05 1.1 - removed UDP
###############################################################################

# DNS-over-TLS provider Foundation for Applied Privacy AUSTRIA
# Need to bypass GeoIP filters from both FORWARDFW and OUTGOINGFW
# NOTE: We do NOT support plain DNS over UDP/53 on our resolvers.
#  location lookup 109.70.100.134
#  Network                 : 109.70.100.0/24
#  Country                 : Austria
#  Autonomous System       : AS208323 - Foundation for Applied Privacy
#  Anonymous Proxy         : yes

CHAINS="FORWARDFW CUSTOMFORWARD"
TCP_PORTS="80,443,53,853"
#UDP_PORTS="53"
DEST_IP="109.70.100.0/24"

#TCP
for chain in ${CHAINS}; do
    iptables -t filter -L "$chain" >/dev/null 2>&1 || continue
    iptables -t filter -C "$chain" -p tcp -m multiport --dports "$TCP_PORTS" -d "$DEST_IP" -j RETURN 2>/dev/null && \
	iptables --wait -t filter -D "$chain" -p tcp -m multiport --dports "$TCP_PORTS" -d "$DEST_IP" -j RETURN
done

#UDP
#for chain in ${CHAINS}; do
#    iptables -t filter -L "$chain" >/dev/null 2>&1 || continue
#    iptables -t filter -C "$chain" -p udp -m multiport --dports "$UDP_PORTS" -d "$DEST_IP" -j RETURN 2>/dev/null || \
#	iptables --wait -t filter -I "$chain" -p udp -m multiport --dports "$UDP_PORTS" -d "$DEST_IP" -j RETURN
#done
