#!/bin/sh
###############################################################################
# $FILENAME
# Generated by generate_fw_modules_exceptions.sh
# Version: 2026-01-17
###############################################################################


iptables --wait -t filter -A CUSTOMFORWARD -p tcp -m multiport --dports 80,443 -d 43.200.186.155/32 -j LOG --log-prefix "LGTV-UPDATES " --log-level 4
iptables --wait -t filter -A CUSTOMFORWARD -p tcp -m multiport --dports 80,443 -d 43.200.186.155/32 -j ACCEPT
iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp -m multiport --dports 80,443 -d 43.200.186.155/32 -j LOG --log-prefix "LGTV-UPDATES " --log-level 4
iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp -m multiport --dports 80,443 -d 43.200.186.155/32 -j ACCEPT

iptables --wait -t filter -A CUSTOMFORWARD -p tcp -m multiport --dports 80,443 -d 3.34.80.17/32 -j LOG --log-prefix "LGTV-UPDATES " --log-level 4
iptables --wait -t filter -A CUSTOMFORWARD -p tcp -m multiport --dports 80,443 -d 3.34.80.17/32 -j ACCEPT
iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp -m multiport --dports 80,443 -d 3.34.80.17/32 -j LOG --log-prefix "LGTV-UPDATES " --log-level 4
iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp -m multiport --dports 80,443 -d 3.34.80.17/32 -j ACCEPT

