#!/bin/sh
###############################################################################
# $FILENAME
# Generated by generate_fw_modules.sh
# Version: 2026-01-17
###############################################################################


# PI - OSMC
iptables --wait -t nat -I CUSTOMPREROUTING -s 192.168.10.4 -j ACCEPT
iptables --wait -t filter -I OUTGOINGFW -p tcp --dport 443 -s 192.168.10.4 -j ACCEPT
iptables --wait -t filter -I OUTGOINGFW -p tcp --dport 80  -s 192.168.10.4 -j ACCEPT

