#!/bin/sh
###############################################################################
# $FILENAME
# Generated by generate_fw_modules.sh
# Version: 2026-01-17
###############################################################################


# PI - OSMC
iptables --wait -t nat -D CUSTOMPREROUTING -s 192.168.10.4 -j ACCEPT 2>/dev/null || true
iptables --wait -t filter -D OUTGOINGFW -p tcp --dport 443 -s 192.168.10.4 -j ACCEPT 2>/dev/null || true
iptables --wait -t filter -D OUTGOINGFW -p tcp --dport 80  -s 192.168.10.4 -j ACCEPT 2>/dev/null || true

