#!/bin/sh
###############################################################################
# $FILENAME
# Generated by generate_fw_modules.sh
# Version: 2026-01-17
###############################################################################


# Revolut IP located in USA but still blocked
iptables --wait -t filter -A CUSTOMFORWARD -p tcp --dport 443 -d 35.201.77.50 -j ACCEPT
iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp --dport 443 -d 35.201.77.50 -j ACCEPT

