#!/bin/sh
###############################################################################
# $FILENAME
# Generated by generate_fw_modules_exceptions.sh
# Version: 2026-01-17
###############################################################################


iptables --wait -t filter -A CUSTOMFORWARD -p tcp -m multiport --dports 80,443 -d 163.171.132.0/24 -j ACCEPT
iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp -m multiport --dports 80,443 -d 163.171.132.0/24 -j ACCEPT
iptables --wait -t filter -A CUSTOMFORWARD -p tcp -m multiport --dports 80,443 -d 163.171.133.0/24 -j ACCEPT
iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp -m multiport --dports 80,443 -d 163.171.133.0/24 -j ACCEPT

