#!/bin/sh
###############################################################################
# $FILENAME
# Generated by generate_fw_modules.sh
# Version: 2026-01-17
###############################################################################


# sdcard.org - Japan
iptables --wait -t filter -A CUSTOMFORWARD -p tcp --dport 443 -d 150.60.244.104 -j ACCEPT
iptables --wait -t filter -A CUSTOMOUTPUT  -p tcp --dport 443 -d 150.60.244.104 -j ACCEPT

