#!/bin/sh
###############################################################################
# $FILENAME
# Generated by generate_fw_modules_exceptions.sh
# Version: 2026-01-17
###############################################################################


iptables --wait -t filter -I OUTGOINGFW -p tcp --dport 43 -d 0.0.0.0/0 -j RETURN
iptables --wait -t filter -I OUTGOINGFW -p tcp --dport 443 -d 203.119.96.0/20 -j RETURN
iptables --wait -t filter -I OUTGOINGFW -p tcp --dport 443 -d 202.12.29.0/24 -j RETURN
iptables --wait -t filter -I OUTGOINGFW -p tcp --dport 443 -d 200.3.12.0/22 -j RETURN

iptables --wait -t filter -I FORWARDFW  -p tcp --dport 43 -d 0.0.0.0/0 -j RETURN
iptables --wait -t filter -I FORWARDFW  -p tcp --dport 443 -d 203.119.96.0/20 -j RETURN
iptables --wait -t filter -I FORWARDFW  -p tcp --dport 443 -d 202.12.29.0/24 -j RETURN
iptables --wait -t filter -I FORWARDFW  -p tcp --dport 443 -d 200.3.12.0/22 -j RETURN

