#!/bin/sh
###############################################################################
# $FILENAME
# Generated by generate_fw_modules.sh
# Version: 2026-01-17
###############################################################################


# IANA / APNIC / LACNIC
iptables --wait -t filter -D OUTGOINGFW -p tcp --dport 43 -d 0.0.0.0/0 -j RETURN 2>/dev/null || true
iptables --wait -t filter -D FORWARDFW  -p tcp --dport 43 -d 0.0.0.0/0 -j RETURN 2>/dev/null || true

